use std::collections::HashMap;
use std::path::{Path, PathBuf};

use async_trait::async_trait;
use cainome::parser::tokens::{Composite, CompositeType, Function, Token};
use convert_case::Casing;
use dojo_world::contracts::naming;

use crate::error::BindgenResult;
use crate::plugins::BuiltinPlugin;
use crate::{DojoContract, DojoData, DojoModel};

pub struct TypeScriptV2Plugin {}

impl TypeScriptV2Plugin {
    pub fn new() -> Self {
        Self {}
    }

    // Maps cairo types to TypeScript defined types
    fn map_type(token: &Token) -> String {
        match token.type_name().as_str() {
            "bool" => "boolean".to_string(),
            "u8" => "number".to_string(),
            "u16" => "number".to_string(),
            "u32" => "number".to_string(),
            "u64" => "bigint".to_string(),
            "u128" => "bigint".to_string(),
            "u256" => "bigint".to_string(),
            "usize" => "number".to_string(),
            "felt252" => "string".to_string(),
            "bytes31" => "string".to_string(),
            "ClassHash" => "string".to_string(),
            "ContractAddress" => "string".to_string(),
            "ByteArray" => "string".to_string(),
            "array" => {
                if let Token::Array(array) = token {
                    format!("{}[]", TypeScriptV2Plugin::map_type(&array.inner))
                } else {
                    panic!("Invalid array token: {:?}", token);
                }
            }
            "tuple" => {
                if let Token::Tuple(tuple) = token {
                    let inners = tuple
                        .inners
                        .iter()
                        .map(TypeScriptV2Plugin::map_type)
                        .collect::<Vec<String>>()
                        .join(", ");
                    format!("[{}]", inners)
                } else {
                    panic!("Invalid tuple token: {:?}", token);
                }
            }

            _ => {
                let mut type_name = token.type_name();

                if let Token::Composite(composite) = token {
                    if !composite.generic_args.is_empty() {
                        type_name += &format!(
                            "<{}>",
                            composite
                                .generic_args
                                .iter()
                                .map(|(_, t)| TypeScriptV2Plugin::map_type(t))
                                .collect::<Vec<_>>()
                                .join(", ")
                        )
                    }
                }

                type_name
            }
        }
    }

    fn generate_header() -> String {
        format!(
            "// Generated by dojo-bindgen on {}. Do not modify this file manually.\n",
            chrono::Utc::now().to_rfc2822()
        )
    }

    fn generate_imports() -> String {
        "import { Account } from \"starknet\";
import {
    Clause,
    Client,
    ModelClause,
    createClient,
    valueToToriiValueAndOperator,
} from \"@dojoengine/torii-client\";
import {
    LOCAL_KATANA,
    LOCAL_RELAY,
    LOCAL_TORII,
    createManifestFromJson,
} from \"@dojoengine/core\";"
            .to_string()
    }

    fn generate_query_types(models: &[&DojoModel]) -> String {
        let mut query_fields = Vec::new();
        let mut result_mapping = Vec::new();

        for model in models {
            query_fields.push(format!(
                "{model_name}: ModelClause<{model_name}>;",
                model_name = naming::get_name_from_tag(&model.tag)
            ));

            result_mapping.push(format!(
                "{model_name}: {model_name};",
                model_name = naming::get_name_from_tag(&model.tag)
            ));
        }

        format!(
            "type Query = Partial<{{
    {query_fields}
}}>;

type ResultMapping = {{
    {result_mapping}
}};

type QueryResult<T extends Query> = {{
    [K in keyof T]: K extends keyof ResultMapping ? ResultMapping[K] : never;
}};

// Only supports a single model for now, since torii doesn't support multiple models
// And inside that single model, there's only support for a single query.
function convertQueryToToriiClause(query: Query): Clause | undefined {{
    const [model, clause] = Object.entries(query)[0];

    if (Object.keys(clause).length === 0) {{
        return undefined;
    }}

    const clauses: Clause[] = Object.entries(clause).map(([key, value]) => {{
        return {{
            Member: {{
                model,
                member: key,
                ...valueToToriiValueAndOperator(value),
            }},
        }} satisfies Clause;
    }});

    return clauses[0];
}}",
            query_fields = query_fields.join("\n    "),
            result_mapping = result_mapping.join("\n    "),
        )
    }

    fn generate_model_types(models: &[&DojoModel], handled_tokens: &mut Vec<Composite>) -> String {
        let mut out = String::new();

        for model in models {
            let tokens = &model.tokens;

            for token in &tokens.structs {
                if handled_tokens.iter().any(|t| t.type_name() == token.type_name()) {
                    continue;
                }

                handled_tokens.push(token.to_composite().unwrap().to_owned());
                out += TypeScriptV2Plugin::format_struct(token.to_composite().unwrap()).as_str();
            }

            for token in &tokens.enums {
                if handled_tokens.iter().any(|t| t.type_name() == token.type_name()) {
                    continue;
                }

                handled_tokens.push(token.to_composite().unwrap().to_owned());
                out += TypeScriptV2Plugin::format_enum(token.to_composite().unwrap()).as_str();
            }

            out += "\n";
        }

        out
    }

    fn generate_base_calls_class() -> String {
        "class BaseCalls {
    contractAddress: string;
    account?: Account;

    constructor(contractAddress: string, account?: Account) {
        this.account = account;
        this.contractAddress = contractAddress;
    }

    async execute(entrypoint: string, calldata: any[] = []): Promise<void> {
        if (!this.account) {
            throw new Error(\"No account set to interact with dojo_starter\");
        }

        await this.account.execute(
            {
                contractAddress: this.contractAddress,
                entrypoint,
                calldata,
            },
            undefined,
            {
                maxFee: 0,
            }
        );
    }
}
"
        .to_string()
    }

    fn generate_contracts(contracts: &[&DojoContract], handled_tokens: &[Composite]) -> String {
        let mut out = String::new();

        for contract in contracts {
            let systems = contract
                .systems
                .iter()
                .map(|system| {
                    TypeScriptV2Plugin::format_system(system.to_function().unwrap(), handled_tokens)
                })
                .collect::<Vec<String>>()
                .join("\n\n    ");

            out += &format!(
                "class {}Calls extends BaseCalls {{
    constructor(contractAddress: string, account?: Account) {{
        super(contractAddress, account);
    }}

    {}
}}
",
                TypeScriptV2Plugin::formatted_contract_name(&contract.tag)
                    .to_case(convert_case::Case::Pascal),
                systems,
            );
        }

        out
    }

    fn generate_initial_params(contracts: &[&DojoContract]) -> String {
        let system_addresses = contracts
            .iter()
            .map(|contract| {
                format!(
                    "{}Address: string;",
                    TypeScriptV2Plugin::formatted_contract_name(&contract.tag)
                        .to_case(convert_case::Case::Camel)
                )
            })
            .collect::<Vec<String>>()
            .join("\n    ");

        format!(
            "type InitialParams = GeneralParams &
    (
        | {{
                rpcUrl?: string;
                worldAddress: string;
                {system_addresses}
            }}
        | {{
                manifest: any;
            }}
    );"
        )
    }

    fn generate_world_class(world_name: &String, contracts: &[&DojoContract]) -> String {
        let mut out = String::new();

        out += "type GeneralParams = {
    toriiUrl?: string;
    relayUrl?: string;
    account?: Account;
};";

        out += "\n\n";

        out += TypeScriptV2Plugin::generate_initial_params(contracts).as_str();

        out += "\n\n";

        let system_properties = contracts
            .iter()
            .map(|contract| {
                format!(
                    "{camel_case_name}: {pascal_case_name}Calls;
    {camel_case_name}Address: string;",
                    camel_case_name = TypeScriptV2Plugin::formatted_contract_name(&contract.tag)
                        .to_case(convert_case::Case::Camel),
                    pascal_case_name = TypeScriptV2Plugin::formatted_contract_name(&contract.tag)
                        .to_case(convert_case::Case::Pascal)
                )
            })
            .collect::<Vec<String>>()
            .join("\n    ");

        let system_address_initializations = contracts
            .iter()
            .map(|contract| {
                format!(
                    "const {contract_name}Address = config.contracts.find(
                (contract) =>
                    contract.name === \"dojo_starter::systems::{contract_name}::{contract_name}\"
            )?.address;

            if (!{contract_name}Address) {{
                throw new Error(\"No {contract_name} contract found in the manifest\");
            }}

            this.{contract_name}Address = {contract_name}Address;",
                    contract_name = TypeScriptV2Plugin::formatted_contract_name(&contract.tag)
                        .to_case(convert_case::Case::Camel)
                )
            })
            .collect::<Vec<String>>()
            .join("\n    ");

        let system_address_initializations_from_params = contracts
            .iter()
            .map(|contract| {
                format!(
                    "this.{camel_case_name}Address = params.{camel_case_name}Address;",
                    camel_case_name = TypeScriptV2Plugin::formatted_contract_name(&contract.tag)
                        .to_case(convert_case::Case::Camel),
                )
            })
            .collect::<Vec<String>>()
            .join("\n    ");

        let system_initializations = contracts
            .iter()
            .map(|contract| {
                format!(
                    "this.{camel_case_name} = new \
                     {pascal_case_name}Calls(this.{camel_case_name}Address, this._account);",
                    camel_case_name = TypeScriptV2Plugin::formatted_contract_name(&contract.tag)
                        .to_case(convert_case::Case::Camel),
                    pascal_case_name = TypeScriptV2Plugin::formatted_contract_name(&contract.tag)
                        .to_case(convert_case::Case::Pascal)
                )
            })
            .collect::<Vec<String>>()
            .join("\n    ");

        let formatted_world_name = world_name.to_case(convert_case::Case::Pascal);

        out += &format!(
            "export class {formatted_world_name} {{
    rpcUrl: string;
    toriiUrl: string;
    toriiPromise: Promise<Client>;
    relayUrl: string;
    worldAddress: string;
    private _account?: Account;
    {system_properties}

    constructor(params: InitialParams) {{
        if (\"manifest\" in params) {{
            const config = createManifestFromJson(params.manifest);
            this.rpcUrl = config.world.metadata.rpc_url;
            this.worldAddress = config.world.address;

            {system_address_initializations}
        }} else {{
            this.rpcUrl = params.rpcUrl || LOCAL_KATANA;
            this.worldAddress = params.worldAddress;
            {system_address_initializations_from_params}
        }}
        this.toriiUrl = params.toriiUrl || LOCAL_TORII;
        this.relayUrl = params.relayUrl || LOCAL_RELAY;
        this._account = params.account;
        {system_initializations}

        this.toriiPromise = createClient([], {{
            rpcUrl: this.rpcUrl,
            toriiUrl: this.toriiUrl,
            worldAddress: this.worldAddress,
            relayUrl: this.relayUrl,
        }});
    }}

    get account(): Account | undefined {{
        return this._account;
    }}

    set account(account: Account) {{
        this._account = account;
        {system_initializations}
    }}

    async query<T extends Query>(query: T, limit = 10, offset = 0) {{
        const torii = await this.toriiPromise;

        return {{
            torii,
            findEntities: async () => this.findEntities(query, limit, offset),
        }};
    }}

    async findEntities<T extends Query>(query: T, limit = 10, offset = 0) {{
        const torii = await this.toriiPromise;

        const clause = convertQueryToToriiClause(query);

        const toriiResult = await torii.getEntities({{
            limit,
            offset,
            clause,
        }});

        return toriiResult as Record<string, QueryResult<T>>;
    }}

    async findEntity<T extends Query>(query: T) {{
        const result = await this.findEntities(query, 1);

        if (Object.values(result).length === 0) {{
            return undefined;
        }}

        return Object.values(result)[0] as QueryResult<T>;
    }}
}}"
        );

        out
    }

    // Token should be a struct
    // This will be formatted into a TypeScript interface
    // using TypeScript defined types
    fn format_struct(token: &Composite) -> String {
        let mut native_fields: Vec<String> = Vec::new();

        for field in &token.inners {
            let mapped = TypeScriptV2Plugin::map_type(&field.token);
            native_fields.push(format!("{}: {};", field.name, mapped));
        }

        format!(
            "
// Type definition for `{path}` struct
export interface {name} {{
    {native_fields}
}}
",
            path = token.type_path,
            name = token.type_name(),
            native_fields = native_fields.join("\n    ")
        )
    }

    // Token should be an enum
    // This will be formatted into a C# enum
    // Enum is mapped using index of cairo enum
    fn format_enum(token: &Composite) -> String {
        let mut name = token.type_name();
        if !token.generic_args.is_empty() {
            name += &format!(
                "<{}>",
                token.generic_args.iter().map(|(n, _)| n.clone()).collect::<Vec<_>>().join(", ")
            )
        }

        let mut result = format!(
            "
// Type definition for `{}` enum
type {} = ",
            token.type_path, name
        );

        let mut variants = Vec::new();

        for field in &token.inners {
            let field_type = TypeScriptV2Plugin::map_type(&field.token).replace("()", "");

            let variant_definition = if field_type.is_empty() {
                // No associated data
                format!("{{ type: '{}'; }}", field.name)
            } else {
                // With associated data
                format!("{{ type: '{}'; data: {}; }}", field.name, field_type)
            };

            variants.push(variant_definition);
        }

        result += &variants.join(" | ");

        result
    }

    // Formats a system into a JS method used by the contract class
    // Handled tokens should be a list of all structs and enums used by the contract
    // Such as a set of referenced tokens from a model
    fn format_system(system: &Function, handled_tokens: &[Composite]) -> String {
        let args = system
            .inputs
            .iter()
            .map(|arg| {
                format!(
                    "{}: {}",
                    arg.0,
                    if TypeScriptV2Plugin::map_type(&arg.1) == arg.1.type_name() {
                        arg.1.type_name()
                    } else {
                        TypeScriptV2Plugin::map_type(&arg.1)
                    }
                )
            })
            .collect::<Vec<String>>()
            .join(", ");

        let calldata = system
            .inputs
            .iter()
            .map(|arg| {
                let token = &arg.1;
                let type_name = &arg.0;

                match handled_tokens.iter().find(|t| t.type_name() == token.type_name()) {
                    Some(t) => {
                        // Need to flatten the struct members.
                        match t.r#type {
                            CompositeType::Struct => t
                                .inners
                                .iter()
                                .map(|field| format!("props.{}.{}", type_name, field.name))
                                .collect::<Vec<String>>()
                                .join(",\n                    "),
                            _ => type_name.to_string(),
                        }
                    }
                    None => type_name.to_string(),
                }
            })
            .collect::<Vec<String>>()
            .join(",\n                ");

        format!(
            "async {pretty_system_name}({args}): Promise<void> {{
        try {{
            await this.execute(\"{system_name}\", [{calldata}])
        }} catch (error) {{
            console.error(\"Error executing {pretty_system_name}:\", error);
            throw error;
        }}
    }}",
            pretty_system_name = system.name.to_case(convert_case::Case::Camel),
            // formatted args to use our mapped types
            args = args,
            system_name = system.name,
            // calldata for execute
            calldata = calldata
        )
    }

    // Formats a contract tag into a pretty contract name
    // eg. dojo_examples-actions -> Actions
    fn formatted_contract_name(tag: &str) -> String {
        naming::capitalize(&naming::get_name_from_tag(tag))
    }

    fn generate_code_content(data: &DojoData) -> String {
        let mut handled_tokens = Vec::<Composite>::new();
        let models = data.models.values().collect::<Vec<_>>();
        let contracts = data.contracts.values().collect::<Vec<_>>();

        let mut code = String::new();
        code += TypeScriptV2Plugin::generate_header().as_str();
        code += TypeScriptV2Plugin::generate_imports().as_str();
        code += "\n";
        code += TypeScriptV2Plugin::generate_model_types(models.as_slice(), &mut handled_tokens)
            .as_str();
        code += "\n";
        code += TypeScriptV2Plugin::generate_base_calls_class().as_str();
        code += "\n";
        code +=
            TypeScriptV2Plugin::generate_contracts(contracts.as_slice(), &handled_tokens).as_str();
        code += "\n";
        code += TypeScriptV2Plugin::generate_query_types(models.as_slice()).as_str();
        code += "\n";
        code += TypeScriptV2Plugin::generate_world_class(&data.world.name, contracts.as_slice())
            .as_str();

        code
    }
}

#[async_trait]
impl BuiltinPlugin for TypeScriptV2Plugin {
    async fn generate_code(&self, data: &DojoData) -> BindgenResult<HashMap<PathBuf, Vec<u8>>> {
        let code: String = TypeScriptV2Plugin::generate_code_content(data);

        let mut out: HashMap<PathBuf, Vec<u8>> = HashMap::new();
        let output_path = Path::new(&format!("{}.ts", data.world.name)).to_owned();

        out.insert(output_path, code.as_bytes().to_vec());

        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::io::Read;

    use dojo_test_utils::setup::TestSetup;
    use scarb_interop::{MetadataDojoExt, Profile};

    use super::*;
    use crate::gather_dojo_data;

    // Uncomment once bindings support arrays.
    #[ignore]
    #[test]
    fn test_output() {
        let mut expected_output = String::new();
        let mut file =
            fs::File::open("src/test_data/mocks/dojo_examples.ts").expect("file not found");
        file.read_to_string(&mut expected_output).expect("error reading file");

        let expected_output_without_header =
            expected_output.lines().skip(1).collect::<Vec<&str>>().join("\n");

        let setup = TestSetup::from_examples("../dojo/core", "../../examples/");
        let metadata = setup.load_metadata("spawn-and-move", Profile::DEV);

        let profile_config = metadata.load_dojo_profile_config().unwrap();

        let skip_migrations = if let Some(migration) = profile_config.migration {
            let mut skip_migration = vec![];
            if let Some(skip_contracts) = migration.skip_contracts {
                skip_migration.extend(skip_contracts);
            }
            Some(skip_migration)
        } else {
            None
        };

        let data = gather_dojo_data(
            setup.manifest_path("spawn-and-move"),
            "dojo_examples",
            "dev",
            skip_migrations,
        )
        .unwrap();

        let actual_output = TypeScriptV2Plugin::generate_code_content(&data);
        let actual_output_without_header =
            actual_output.lines().skip(1).collect::<Vec<&str>>().join("\n");

        // This test currently is very naive, but DojoData is unsorted, so the output
        // can change between tests. This is a temporary solution until we have a better
        // way to test this.
        assert_eq!(actual_output_without_header.len(), 7592);
        assert_eq!(expected_output_without_header.len(), 7592);
    }
}
