using System;
using Dojo;
using Dojo.Starknet;
// Generated by dojo-bindgen on Thu, 1 Feb 2024 16:18:57 +0000. Do not modify this file manually.
// Type definition for `dojo_examples::models::Direction` enum
public enum Direction {
    None,
    Left,
    Right,
    Up,
    Down,
}


// Model definition for `dojo_examples::models::Moves` model
public class Moves : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("remaining")]
    public byte remaining;

    [ModelField("last_direction")]
    public Direction last_direction;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        