using System;
using Dojo;
using Dojo.Starknet;
// Generated by dojo-bindgen on Thu, 1 Feb 2024 16:18:57 +0000. Do not modify this file manually.
// Type definition for `dojo_examples::models::Vec2` struct
[Serializable]
public struct Vec2 {
    public uint x;
    public uint y;
}


// Model definition for `dojo_examples::models::Position` model
public class Position : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("vec")]
    public Vec2 vec;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        