#!/usr/bin/env bash
set -e

echo Installing dojoup...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
DOJO_DIR=${DOJO_DIR-"$BASE_DIR/.dojo"}
DOJO_BIN_DIR="$DOJO_DIR/bin"
DOJO_DOJOUP_DIR="$DOJO_DIR/dojoup"
DOJO_MAN_DIR="$DOJO_DIR/share/man/man1"

BIN_URL="https://raw.githubusercontent.com/dojoengine/dojo/main/dojoup/dojoup"
BIN_PATH="$DOJO_DOJOUP_DIR/dojoup"

# Create the .dojo bin directory and dojoup binary if it doesn't exist.
mkdir -p $DOJO_BIN_DIR
mkdir -p $DOJO_DOJOUP_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Create the man directory for future man files if it doesn't exist.
mkdir -p $DOJO_MAN_DIR

# Create env file with PATH configuration
ENV_FILE="$DOJO_DIR/env"
cat > $ENV_FILE << EOF
#!/bin/sh
# dojoup shell setup
# affix colons on either side of \$PATH to simplify matching
case ":\${PATH}:" in
    *:"$DOJO_BIN_DIR":*)
        ;;
    *)
        # Appending path for dojo binary directory
        export PATH="\$PATH:$DOJO_BIN_DIR"
        ;;
esac

case ":\${PATH}:" in
    *:"$DOJO_DOJOUP_DIR":*)
        ;;
    *)
        # Appending path for dojoup directory
        export PATH="\$PATH:$DOJO_DOJOUP_DIR"
        ;;
esac
EOF

SOURCE_COMMAND=". \"$ENV_FILE\""

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
    *)
		echo "Could not detect your current shell."
        echo
        echo "You may need to manually source the"
        echo "corresponding env file under $DOJO_DIR."
        echo
        echo "This is usually done by running the following (note the leading DOT):"
        echo "$SOURCE_COMMAND            # For sh/bash/zsh/ash/dash/pdksh"
        exit 1
esac

if ! grep -q "$SOURCE_COMMAND" $PROFILE; then
    echo >> $PROFILE && echo "$SOURCE_COMMAND" >> $PROFILE
    . $PROFILE
fi

# echo && echo "Detected your preferred shell is ${PREF_SHELL} and added dojoup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use dojoup."
# echo "Then, simply run 'dojoup install' to install Dojo."

echo && echo "Dojoup is installed now."
echo "Simply run 'dojoup install' to install a Dojo toolchain."
