#!/usr/bin/env bash
set -e

echo Installing dojoup...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
DOJO_DIR=${DOJO_DIR-"$BASE_DIR/.dojo"}
DOJO_BIN_DIR="$DOJO_DIR/bin"
DOJO_MAN_DIR="$DOJO_DIR/share/man/man1"

BIN_URL="https://raw.githubusercontent.com/dojoengine/dojo/main/dojoup/dojoup"
BIN_PATH="$DOJO_BIN_DIR/dojoup"


# Create the .dojo bin directory and dojoup binary if it doesn't exist.
mkdir -p $DOJO_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Create the man directory for future man files if it doesn't exist.
mkdir -p $DOJO_MAN_DIR

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "dojoup: could not detect shell, manually add ${DOJO_BIN_DIR} to your PATH."
    exit 1
esac

# Only add dojoup if it isn't already in PATH.
if [[ ":$PATH:" != *":${DOJO_BIN_DIR}:"* ]]; then
    # Add the dojoup directory to the path and ensure the old PATH variables remain.
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$DOJO_BIN_DIR\"" >> $PROFILE
fi

# Warn MacOS users that they may need to manually install libusb via Homebrew:
if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib && ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
    echo && echo "warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb)."
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added dojoup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use dojoup."
echo "Then, simply run 'dojoup' to install Dojo."