// AUTOGENERATED FILE, DO NOT EDIT.
// To generate the bindings, please run `cargo run --bin dojo-world-abigen` instead.
use cainome::rs::abigen;

abigen!(
    ModelContract,
    r#"[
  {
    "type": "function",
    "name": "selector",
    "inputs": [],
    "outputs": [
      {
        "type": "core::felt252"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "enum",
    "name": "core::option::Option::<core::integer::u32>",
    "variants": [
      {
        "name": "Some",
        "type": "core::integer::u32"
      },
      {
        "name": "None",
        "type": "()"
      }
    ]
  },
  {
    "type": "function",
    "name": "unpacked_size",
    "inputs": [],
    "outputs": [
      {
        "type": "core::option::Option::<core::integer::u32>"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "function",
    "name": "packed_size",
    "inputs": [],
    "outputs": [
      {
        "type": "core::option::Option::<core::integer::u32>"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "struct",
    "name": "core::array::Span::<core::integer::u8>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<core::integer::u8>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "dojo::meta::layout::FieldLayout",
    "members": [
      {
        "name": "selector",
        "type": "core::felt252"
      },
      {
        "name": "layout",
        "type": "dojo::meta::layout::Layout"
      }
    ]
  },
  {
    "type": "struct",
    "name": "core::array::Span::<dojo::meta::layout::FieldLayout>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<dojo::meta::layout::FieldLayout>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "core::array::Span::<dojo::meta::layout::Layout>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<dojo::meta::layout::Layout>"
      }
    ]
  },
  {
    "type": "enum",
    "name": "dojo::meta::layout::Layout",
    "variants": [
      {
        "name": "Fixed",
        "type": "core::array::Span::<core::integer::u8>"
      },
      {
        "name": "Struct",
        "type": "core::array::Span::<dojo::meta::layout::FieldLayout>"
      },
      {
        "name": "Tuple",
        "type": "core::array::Span::<dojo::meta::layout::Layout>"
      },
      {
        "name": "Array",
        "type": "core::array::Span::<dojo::meta::layout::Layout>"
      },
      {
        "name": "ByteArray",
        "type": "()"
      },
      {
        "name": "Enum",
        "type": "core::array::Span::<dojo::meta::layout::FieldLayout>"
      }
    ]
  },
  {
    "type": "function",
    "name": "layout",
    "inputs": [],
    "outputs": [
      {
        "type": "dojo::meta::layout::Layout"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "struct",
    "name": "core::array::Span::<core::felt252>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<core::felt252>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "dojo::meta::introspect::Member",
    "members": [
      {
        "name": "name",
        "type": "core::felt252"
      },
      {
        "name": "attrs",
        "type": "core::array::Span::<core::felt252>"
      },
      {
        "name": "ty",
        "type": "dojo::meta::introspect::Ty"
      }
    ]
  },
  {
    "type": "struct",
    "name": "core::array::Span::<dojo::meta::introspect::Member>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<dojo::meta::introspect::Member>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "dojo::meta::introspect::Struct",
    "members": [
      {
        "name": "name",
        "type": "core::felt252"
      },
      {
        "name": "attrs",
        "type": "core::array::Span::<core::felt252>"
      },
      {
        "name": "children",
        "type": "core::array::Span::<dojo::meta::introspect::Member>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "core::array::Span::<(core::felt252, dojo::meta::introspect::Ty)>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<(core::felt252, dojo::meta::introspect::Ty)>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "dojo::meta::introspect::Enum",
    "members": [
      {
        "name": "name",
        "type": "core::felt252"
      },
      {
        "name": "attrs",
        "type": "core::array::Span::<core::felt252>"
      },
      {
        "name": "children",
        "type": "core::array::Span::<(core::felt252, dojo::meta::introspect::Ty)>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "core::array::Span::<dojo::meta::introspect::Ty>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<dojo::meta::introspect::Ty>"
      }
    ]
  },
  {
    "type": "enum",
    "name": "dojo::meta::introspect::Ty",
    "variants": [
      {
        "name": "Primitive",
        "type": "core::felt252"
      },
      {
        "name": "Struct",
        "type": "dojo::meta::introspect::Struct"
      },
      {
        "name": "Enum",
        "type": "dojo::meta::introspect::Enum"
      },
      {
        "name": "Tuple",
        "type": "core::array::Span::<dojo::meta::introspect::Ty>"
      },
      {
        "name": "Array",
        "type": "core::array::Span::<dojo::meta::introspect::Ty>"
      },
      {
        "name": "ByteArray",
        "type": "()"
      }
    ]
  },
  {
    "type": "function",
    "name": "schema",
    "inputs": [],
    "outputs": [
      {
        "type": "dojo::meta::introspect::Ty"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "struct",
    "name": "core::byte_array::ByteArray",
    "members": [
      {
        "name": "data",
        "type": "core::array::Array::<core::bytes_31::bytes31>"
      },
      {
        "name": "pending_word",
        "type": "core::felt252"
      },
      {
        "name": "pending_word_len",
        "type": "core::integer::u32"
      }
    ]
  },
  {
    "type": "struct",
    "name": "dojo::model::metadata::ResourceMetadata",
    "members": [
      {
        "name": "resource_id",
        "type": "core::felt252"
      },
      {
        "name": "metadata_uri",
        "type": "core::byte_array::ByteArray"
      }
    ]
  },
  {
    "type": "function",
    "name": "ensure_abi",
    "inputs": [
      {
        "name": "model",
        "type": "dojo::model::metadata::ResourceMetadata"
      }
    ],
    "outputs": [],
    "state_mutability": "view"
  },
  {
    "type": "event",
    "name": "dojo::model::metadata::resource_metadata::Event",
    "kind": "enum",
    "variants": []
  }
]"#,
type_aliases {
dojo::world::config::Config::Event as DojoConfigEvent;
},derives(Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq, Clone)
);
