// AUTOGENERATED FILE, DO NOT EDIT.
// To generate the bindings, please run `cargo run --bin dojo-world-abigen` instead.
use cainome::rs::abigen;

abigen!(
    ModelContract,
    r#"[
  {
    "type": "function",
    "name": "name",
    "inputs": [],
    "outputs": [
      {
        "type": "core::felt252"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "function",
    "name": "unpacked_size",
    "inputs": [],
    "outputs": [
      {
        "type": "core::integer::u32"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "function",
    "name": "packed_size",
    "inputs": [],
    "outputs": [
      {
        "type": "core::integer::u32"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "struct",
    "name": "core::array::Span::<core::integer::u8>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<core::integer::u8>"
      }
    ]
  },
  {
    "type": "function",
    "name": "layout",
    "inputs": [],
    "outputs": [
      {
        "type": "core::array::Span::<core::integer::u8>"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "struct",
    "name": "core::array::Span::<core::felt252>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<core::felt252>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "core::array::Span::<core::array::Span::<core::felt252>>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<core::array::Span::<core::felt252>>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "dojo::database::introspect::Struct",
    "members": [
      {
        "name": "name",
        "type": "core::felt252"
      },
      {
        "name": "attrs",
        "type": "core::array::Span::<core::felt252>"
      },
      {
        "name": "children",
        "type": "core::array::Span::<core::array::Span::<core::felt252>>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "core::array::Span::<(core::felt252, core::array::Span::<core::felt252>)>",
    "members": [
      {
        "name": "snapshot",
        "type": "@core::array::Array::<(core::felt252, core::array::Span::<core::felt252>)>"
      }
    ]
  },
  {
    "type": "struct",
    "name": "dojo::database::introspect::Enum",
    "members": [
      {
        "name": "name",
        "type": "core::felt252"
      },
      {
        "name": "attrs",
        "type": "core::array::Span::<core::felt252>"
      },
      {
        "name": "children",
        "type": "core::array::Span::<(core::felt252, core::array::Span::<core::felt252>)>"
      }
    ]
  },
  {
    "type": "enum",
    "name": "dojo::database::introspect::Ty",
    "variants": [
      {
        "name": "Primitive",
        "type": "core::felt252"
      },
      {
        "name": "Struct",
        "type": "dojo::database::introspect::Struct"
      },
      {
        "name": "Enum",
        "type": "dojo::database::introspect::Enum"
      },
      {
        "name": "Tuple",
        "type": "core::array::Span::<core::array::Span::<core::felt252>>"
      },
      {
        "name": "Array",
        "type": "core::integer::u32"
      }
    ]
  },
  {
    "type": "function",
    "name": "schema",
    "inputs": [],
    "outputs": [
      {
        "type": "dojo::database::introspect::Ty"
      }
    ],
    "state_mutability": "view"
  },
  {
    "type": "struct",
    "name": "dojo::resource_metadata::ResourceMetadata",
    "members": [
      {
        "name": "resource_id",
        "type": "core::felt252"
      },
      {
        "name": "metadata_uri",
        "type": "core::array::Span::<core::felt252>"
      }
    ]
  },
  {
    "type": "function",
    "name": "ensure_abi",
    "inputs": [
      {
        "name": "model",
        "type": "dojo::resource_metadata::ResourceMetadata"
      }
    ],
    "outputs": [],
    "state_mutability": "view"
  },
  {
    "type": "event",
    "name": "dojo::resource_metadata::resource_metadata::Event",
    "kind": "enum",
    "variants": []
  }
]"#
);
