{
 "title": "Katana",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(up)" } }
  ]
 },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Table Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "katana_db_table_size{table=\"BlockBodyIndices\"}",
     "legendFormat": "BlockBodyIndices"
    },
    {
     "expr": "katana_db_table_size{table=\"BlockHashes\"}",
     "legendFormat": "BlockHashes"
    },
    {
     "expr": "katana_db_table_size{table=\"BlockNumbers\"}",
     "legendFormat": "BlockNumbers"
    },
    {
     "expr": "katana_db_table_size{table=\"BlockStatusses\"}",
     "legendFormat": "BlockStatusses"
    },
    {
     "expr": "katana_db_table_size{table=\"ClassChangeHistory\"}",
     "legendFormat": "ClassChangeHistory"
    },
    {
     "expr": "katana_db_table_size{table=\"ClassDeclarationBlock\"}",
     "legendFormat": "ClassDeclarationBlock"
    },
    {
     "expr": "katana_db_table_size{table=\"ClassDeclarations\"}",
     "legendFormat": "ClassDeclarations"
    },
    {
     "expr": "katana_db_table_size{table=\"CompiledClassHashes\"}",
     "legendFormat": "CompiledClassHashes"
    },
    {
     "expr": "katana_db_table_size{table=\"CompiledClasses\"}",
     "legendFormat": "CompiledClasses"
    },
    {
     "expr": "katana_db_table_size{table=\"ContractInfo\"}",
     "legendFormat": "ContractInfo"
    },
    {
     "expr": "katana_db_table_size{table=\"ContractInfoChangeSet\"}",
     "legendFormat": "ContractInfoChangeSet"
    },
    {
     "expr": "katana_db_table_size{table=\"Headers\"}",
     "legendFormat": "Headers"
    },
    {
     "expr": "katana_db_table_size{table=\"NonceChangeHistory\"}",
     "legendFormat": "NonceChangeHistory"
    },
    {
     "expr": "katana_db_table_size{table=\"Receipts\"}",
     "legendFormat": "Receipts"
    },
    {
     "expr": "katana_db_table_size{table=\"SierraClasses\"}",
     "legendFormat": "SierraClasses"
    },
    {
     "expr": "katana_db_table_size{table=\"StorageChangeHistory\"}",
     "legendFormat": "StorageChangeHistory"
    },
    {
     "expr": "katana_db_table_size{table=\"StorageChangeSet\"}",
     "legendFormat": "StorageChangeSet"
    },
    {
     "expr": "katana_db_table_size{table=\"Transactions\"}",
     "legendFormat": "Transactions"
    },
    {
     "expr": "katana_db_table_size{table=\"TxBlocks\"}",
     "legendFormat": "TxBlocks"
    },
    {
     "expr": "katana_db_table_size{table=\"TxHashes\"}",
     "legendFormat": "TxHashes"
    },
    {
     "expr": "katana_db_table_size{table=\"TxNumbers\"}",
     "legendFormat": "TxNumbers"
    },
    {
     "expr": "katana_db_table_size{table=\"TxTraces\"}",
     "legendFormat": "TxTraces"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "stat",
   "description": "Total storage capacity of the database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Freelist Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "katana_db_freelist", "legendFormat": "Freelist" }
   ]
  },
  { "title": "Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "L1 Gas Processed",
   "type": "timeseries",
   "description": "The total amount of L1 gas that has been processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "katana_block_producer_l1_gas_processed_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cairo Steps Processed",
   "type": "timeseries",
   "description": "The total amount of Cairo steps that has been processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "katana_block_producer_cairo_steps_processed_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RPC Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(katana_rpc_server_connections_connections_opened{instance=~\"$instance\"} - katana_rpc_server_connections_connections_closed{instance=~\"$instance\"}) by (transport)",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Request Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg(max_over_time(katana_rpc_server_connections_request_time_seconds{instance=~\"$instance\"}[$__rate_interval]) > 0) by (quantile)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum call latency per method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(max_over_time(katana_rpc_server_calls_time_seconds[$__rate_interval])) by (method) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Call Latency time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "avg(max_over_time(katana_rpc_server_calls_time_seconds{instance=~\"$instance\"}[$__rate_interval]) > 0) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "100% = 1 core",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(katana_process_cpu_seconds_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "katana_process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "Jemalloc Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "katana_jemalloc_active{instance=~\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "katana_jemalloc_allocated{instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "katana_jemalloc_mapped{instance=~\"$instance\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "katana_jemalloc_metadata{instance=~\"$instance\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "katana_jemalloc_resident{instance=~\"$instance\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "katana_jemalloc_retained{instance=~\"$instance\"}",
     "legendFormat": "Retained"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "katana_process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "Open"
    }
   ]
  }
 ]
}