use std::collections::HashMap;
use std::path::{Path, PathBuf};

use async_trait::async_trait;
use cainome::parser::tokens::{Composite, CompositeType, Function, FunctionOutputKind, Token};
use dojo_world::contracts::naming::{self, get_namespace_from_tag};

use crate::error::BindgenResult;
use crate::plugins::BuiltinPlugin;
use crate::{compare_tokens_by_type_name, DojoContract, DojoData, DojoModel};

#[derive(Debug)]
pub struct UnityPlugin {}

impl UnityPlugin {
    pub fn new() -> Self {
        Self {}
    }

    // Maps cairo types to C#/Unity SDK defined types
    fn map_type(token: &Token) -> String {
        match token.type_name().as_str() {
            "i8" => "sbyte".to_string(),
            "i16" => "short".to_string(),
            "i32" => "int".to_string(),
            "i64" => "long".to_string(),
            "i128" => "BigInteger".to_string(),
            "u8" => "byte".to_string(),
            "u16" => "ushort".to_string(),
            "u32" => "uint".to_string(),
            "u64" => "ulong".to_string(),
            "u128" => "BigInteger".to_string(),
            "u256" => "BigInteger".to_string(),
            "usize" => "uint".to_string(),
            "felt252" => "FieldElement".to_string(),
            "bytes31" => "string".to_string(),
            "ClassHash" => "FieldElement".to_string(),
            "ContractAddress" => "FieldElement".to_string(),
            "ByteArray" => "string".to_string(),
            "array" => {
                if let Token::Array(array) = token {
                    format!("{}[]", UnityPlugin::map_type(&array.inner))
                } else {
                    panic!("Invalid array token: {:?}", token);
                }
            }
            "tuple" => {
                if let Token::Tuple(tuple) = token {
                    let inners = tuple
                        .inners
                        .iter()
                        .map(UnityPlugin::map_type)
                        .collect::<Vec<String>>()
                        .join(", ");
                    format!("({})", inners)
                } else {
                    panic!("Invalid tuple token: {:?}", token);
                }
            }

            _ => {
                let mut type_name = token.type_name().to_string();

                if let Token::Composite(composite) = token {
                    if !composite.generic_args.is_empty() {
                        type_name += &format!(
                            "<{}>",
                            composite
                                .generic_args
                                .iter()
                                .map(|(_, t)| UnityPlugin::map_type(t))
                                .collect::<Vec<_>>()
                                .join(", ")
                        )
                    }
                }

                type_name
            }
        }
    }

    fn generated_header() -> String {
        format!(
            "// Generated by dojo-bindgen on {}. Do not modify this file manually.\n",
            chrono::Utc::now().to_rfc2822()
        )
    }

    fn contract_imports() -> String {
        "using System;
using System.Threading.Tasks;
using Dojo;
using Dojo.Starknet;
using UnityEngine;
using dojo_bindings;
using System.Collections.Generic;
using System.Linq;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;
"
        .to_string()
    }

    fn model_imports() -> String {
        "using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;
"
        .to_string()
    }

    // Token should be a struct
    // This will be formatted into a C# struct
    // using C# and unity SDK types
    fn format_struct(token: &Composite) -> String {
        let fields = token
            .inners
            .iter()
            .map(|field| format!("public {} {};", UnityPlugin::map_type(&field.token), field.name))
            .collect::<Vec<String>>()
            .join("\n    ");

        format!(
            "
// Type definition for `{}` struct
[Serializable]
public struct {} {{
    {}
}}
",
            token.type_path,
            token.type_name(),
            fields
        )
    }

    // Token should be an enum
    // This will be formatted into a C# enum
    // Enum is mapped using index of cairo enum
    fn format_enum(token: &Composite) -> String {
        let name = token.type_name();
        let mut name_with_generics = name.clone();
        if !token.generic_args.is_empty() {
            name_with_generics += &format!(
                "<{}>",
                token.generic_args.iter().map(|(n, _)| n.clone()).collect::<Vec<_>>().join(", ")
            );
        }

        let mut result = format!(
            "
// Type definition for `{}` enum
public abstract record {}() : Enum {{",
            token.type_path, name_with_generics
        );

        for field in &token.inners {
            let type_name = UnityPlugin::map_type(&field.token).replace(['(', ')'], "");

            result += format!(
                "\n    public record {}({}) : {name_with_generics};",
                field.name,
                if type_name.is_empty() { type_name } else { format!("{} value", type_name) }
            )
            .as_str();
        }

        result += "\n}\n";

        result
    }

    // Token should be a model
    // This will be formatted into a C# class inheriting from ModelInstance
    // Fields are mapped using C# and unity SDK types
    fn format_model(namespace: &str, model: &Composite) -> String {
        let fields = model
            .inners
            .iter()
            .map(|field| {
                format!(
                    "[ModelField(\"{}\")]\n        public {} {};",
                    field.name,
                    UnityPlugin::map_type(&field.token),
                    field.name,
                )
            })
            .collect::<Vec<String>>()
            .join("\n\n        ");

        format!(
            "
// Model definition for `{}` model
public class {}_{} : ModelInstance {{
    {}

    // Start is called before the first frame update
    void Start() {{
    }}

    // Update is called once per frame
    void Update() {{
    }}
}}

        ",
            model.type_path,
            namespace,
            model.type_name(),
            fields
        )
    }

    // Handles a model definition and its referenced tokens
    // Will map all structs and enums to C# types
    // Will format the model into a C# class
    fn handle_model(
        &self,
        model: &DojoModel,
        handled_tokens: &mut HashMap<String, Composite>,
    ) -> String {
        let mut out = String::new();
        out += UnityPlugin::generated_header().as_str();
        out += UnityPlugin::model_imports().as_str();

        let mut model_struct: Option<&Composite> = None;
        let tokens = &model.tokens;

        let mut sorted_structs = tokens.structs.clone();
        sorted_structs.sort_by(compare_tokens_by_type_name);

        let mut sorted_enums = tokens.enums.clone();
        sorted_enums.sort_by(compare_tokens_by_type_name);

        // Process structs first
        for token in &sorted_structs {
            if handled_tokens.contains_key(&token.type_path()) {
                continue;
            }

            handled_tokens.insert(token.type_path(), token.to_composite().unwrap().to_owned());

            if token.type_name() == naming::get_name_from_tag(&model.tag) {
                model_struct = Some(token.to_composite().unwrap());
                continue;
            }
        }

        let model_struct = model_struct.expect("model struct not found");

        // Handle struct dependencies
        let struct_keys: Vec<String> = handled_tokens
            .iter()
            .filter(|(_, s)| {
                model_struct.inners.iter().any(|inner| {
                    s.r#type == CompositeType::Struct
                        && check_token_in_recursively(&inner.token, &s.type_name())
                        && inner.token.type_name() != "ByteArray"
                })
            })
            .map(|(k, _)| k.clone())
            .collect();

        for key in struct_keys {
            if let Some(s) = handled_tokens.remove(&key) {
                out += UnityPlugin::format_struct(&s).as_str();
            }
        }

        // Process enums
        for token in &sorted_enums {
            if handled_tokens.contains_key(&token.type_path()) {
                continue;
            }

            handled_tokens.insert(token.type_path(), token.to_composite().unwrap().to_owned());
        }

        // Handle enum dependencies
        let enum_keys: Vec<String> = handled_tokens
            .iter()
            .filter(|(_, s)| {
                model_struct.inners.iter().any(|inner| {
                    s.r#type == CompositeType::Enum
                        && check_token_in_recursively(&inner.token, &s.type_name())
                })
            })
            .map(|(k, _)| k.clone())
            .collect();

        for key in enum_keys {
            if let Some(s) = handled_tokens.remove(&key) {
                out += UnityPlugin::format_enum(&s).as_str();
            }
        }

        out += "\n";
        out +=
            UnityPlugin::format_model(&get_namespace_from_tag(&model.tag), model_struct).as_str();

        out
    }

    // Formats a system into a C# method used by the contract class
    // Handled tokens should be a list of all structs and enums used by the contract
    // Such as a set of referenced tokens from a model
    fn format_system(system: &Function) -> String {
        fn handle_arg_recursive(
            arg_name: &str,
            token: &Token,
            // variant name
            // if its an enum variant data
            enum_variant: Option<String>,
        ) -> Vec<(
            // formatted arg
            String,
            // if its an array
            bool,
            // enum name and variant name
            // if its an enum variant data
            Option<String>,
        )> {
            let mapped_type = UnityPlugin::map_type(token);

            match token {
                Token::Composite(t) => {
                    // Need to flatten the struct members.
                    match t.r#type {
                        CompositeType::Struct if t.type_name() == "ByteArray" => vec![(
                            format!("ByteArray.Serialize({}).Select(f => f.Inner)", arg_name),
                            true,
                            enum_variant,
                        )],
                        CompositeType::Unknown | CompositeType::Struct => {
                            let mut tokens = vec![];
                            t.inners.iter().for_each(|f| {
                                tokens.extend(handle_arg_recursive(
                                    &format!("{}.{}", arg_name, f.name),
                                    &f.token,
                                    enum_variant.clone(),
                                ));
                            });

                            tokens
                        }
                        CompositeType::Enum => {
                            let mut tokens = vec![(
                                format!("new FieldElement(Enum.GetIndex({})).Inner", arg_name),
                                false,
                                enum_variant,
                            )];

                            t.inners.iter().for_each(|field| {
                                if let Token::CoreBasic(basic) = &field.token {
                                    // ignore unit type
                                    if basic.type_path == "()" {
                                        return;
                                    }
                                }

                                tokens.extend(handle_arg_recursive(
                                    &format!(
                                        "(({}.{}){}).value",
                                        mapped_type,
                                        field.name.clone(),
                                        arg_name
                                    ),
                                    &field.token,
                                    Some(field.name.clone()),
                                ))
                            });

                            tokens
                        }
                    }
                }
                Token::Array(array) => {
                    let is_inner_array = matches!(array.inner.as_ref(), Token::Array(_));
                    let inner = handle_arg_recursive(
                        &format!("{arg_name}Item"),
                        &array.inner,
                        enum_variant.clone(),
                    );

                    let inners = inner
                        .into_iter()
                        .map(|(arg, _, _)| arg)
                        .collect::<Vec<String>>()
                        .join(", ");

                    vec![
                        (
                            format!("new FieldElement({arg_name}.Length).Inner",),
                            false,
                            enum_variant.clone(),
                        ),
                        (
                            if is_inner_array {
                                format!(
                                    "{arg_name}.SelectMany({arg_name}Item => new \
                                     dojo.FieldElement[] {{ }}.Concat({inners}))"
                                )
                            } else {
                                format!(
                                    "{arg_name}.SelectMany({arg_name}Item => new [] {{ {inners} \
                                     }})"
                                )
                            },
                            true,
                            enum_variant.clone(),
                        ),
                    ]
                }
                Token::Tuple(tuple) => tuple
                    .inners
                    .iter()
                    .enumerate()
                    .flat_map(|(idx, token)| {
                        handle_arg_recursive(
                            &format!("{}.Item{}", arg_name, idx + 1),
                            token,
                            enum_variant.clone(),
                        )
                    })
                    .collect(),
                _ => match mapped_type.as_str() {
                    "FieldElement" => vec![(format!("{}.Inner", arg_name), false, enum_variant)],
                    _ => {
                        vec![(format!("new FieldElement({}).Inner", arg_name), false, enum_variant)]
                    }
                },
            }
        }

        let args = system
            .inputs
            .iter()
            .map(|arg| format!("{} {}", UnityPlugin::map_type(&arg.1), &arg.0))
            .collect::<Vec<String>>()
            .join(", ");

        let calldata = system
            .inputs
            .iter()
            .flat_map(|(name, token)| {
                let tokens = handle_arg_recursive(name, token, None);

                tokens
                    .iter()
                    .map(|(arg, is_array, enum_variant)| {
                        let calldata_op = if *is_array {
                            format!("calldata.AddRange({arg});")
                        } else {
                            format!("calldata.Add({arg});")
                        };

                        if let Some(variant) = enum_variant {
                            let mapped_token = UnityPlugin::map_type(token);
                            let mapped_variant_type = format!("{}.{}", mapped_token, variant);

                            format!("if ({name} is {mapped_variant_type}) {calldata_op}",)
                        } else {
                            calldata_op
                        }
                    })
                    .collect::<Vec<String>>()
            })
            .collect::<Vec<String>>()
            .join("\n\t\t");

        format!(
            "
    // Call the `{system_name}` system with the specified Account and calldata
    // Returns the transaction hash. Use `WaitForTransaction` to wait for the transaction to be \
             confirmed.
    public async Task<FieldElement> {system_name}(Account account{arg_sep}{args}) {{
        List<dojo.FieldElement> calldata = new List<dojo.FieldElement>();
        {calldata}

        return await account.ExecuteRaw(new dojo.Call[] {{
            new dojo.Call{{
                to = new FieldElement(contractAddress).Inner,
                selector = \"{system_name}\",
                calldata = calldata.ToArray()
            }}
        }});
    }}
            ",
            // selector for execute
            system_name = system.name,
            // add comma if we have args
            arg_sep = if !args.is_empty() { ", " } else { "" },
            // formatted args to use our mapped types
            args = args,
            // calldata for execute
            calldata = calldata
        )
    }

    // Formats a contract tag into a pretty contract name
    // eg. dojo_examples-actions.json -> Actions
    fn formatted_contract_name(tag: &str) -> String {
        naming::capitalize(&naming::get_name_from_tag(tag))
    }

    // Handles a contract definition and its underlying systems
    // Will format the contract into a C# class and
    // all systems into C# methods
    // Handled tokens should be a list of all structs and enums used by the contract
    fn handle_contract(&self, contract: &DojoContract) -> String {
        let mut out = String::new();
        out += UnityPlugin::generated_header().as_str();
        out += UnityPlugin::contract_imports().as_str();

        let systems = contract
            .systems
            .iter()
            // we assume systems dont have outputs
            .filter(|s| s.to_function().unwrap().get_output_kind() as u8 == FunctionOutputKind::NoOutput as u8)
            .map(|system| UnityPlugin::format_system(system.to_function().unwrap()))
            .collect::<Vec<String>>()
            .join("\n\n    ");

        out += &format!(
            "
// System definitions for `{}` contract
public class {} : MonoBehaviour {{
    // The address of this contract
    public string contractAddress;

    {}
}}
        ",
            contract.tag,
            // capitalize contract name
            UnityPlugin::formatted_contract_name(&contract.tag),
            systems
        );

        out
    }
}

fn check_token_in_recursively(token: &Token, type_name: &str) -> bool {
    match token {
        Token::Composite(composite) => {
            if composite.type_name() == type_name {
                return true;
            }
            composite.inners.iter().any(|inner| check_token_in_recursively(&inner.token, type_name))
        }
        Token::Array(array) => check_token_in_recursively(&array.inner, type_name),
        Token::Tuple(tuple) => {
            tuple.inners.iter().any(|inner| check_token_in_recursively(inner, type_name))
        }
        _ => token.type_name() == type_name,
    }
}

#[async_trait]
impl BuiltinPlugin for UnityPlugin {
    async fn generate_code(&self, data: &DojoData) -> BindgenResult<HashMap<PathBuf, Vec<u8>>> {
        let mut out: HashMap<PathBuf, Vec<u8>> = HashMap::new();
        let mut handled_tokens = HashMap::<String, Composite>::new();

        let mut models = data.models.iter().collect::<Vec<_>>();
        // Sort models based on their tag to ensure deterministic output.
        models.sort_by(|(_, a), (_, b)| a.tag.cmp(&b.tag));

        // Handle codegen for models
        for (name, model) in &models {
            let models_path = Path::new(&format!("Models/{}.gen.cs", name)).to_owned();

            println!("Generating model: {}", name);
            let code = self.handle_model(model, &mut handled_tokens);

            out.insert(models_path, code.as_bytes().to_vec());
        }

        let mut contracts = data.contracts.iter().collect::<Vec<_>>();
        // Sort contracts based on their tag to ensure deterministic output.
        contracts.sort_by(|(_, a), (_, b)| a.tag.cmp(&b.tag));

        // Handle codegen for systems
        for (name, contract) in &contracts {
            let contracts_path = Path::new(&format!("Contracts/{}.gen.cs", name)).to_owned();

            println!("Generating contract: {}", name);
            let code = self.handle_contract(contract);

            out.insert(contracts_path, code.as_bytes().to_vec());
        }

        Ok(out)
    }
}
