// Generated by dojo-bindgen on Fri, 12 Apr 2024 13:23:24 +0000. Do not modify this file manually.
import { Account } from "starknet";
import {
    Clause,
    Client,
    ModelClause,
    createClient,
    valueToToriiValueAndOperator,
} from "@dojoengine/torii-client";
import { LOCAL_KATANA, createManifestFromJson } from "@dojoengine/core";

// Type definition for `dojo_examples::actions::actions::Moved` struct
export interface Moved {
    player: string;
    direction: Direction;
}

// Type definition for `dojo_examples::models::Direction` enum
export enum Direction {
    None,
    Left,
    Right,
    Up,
    Down,
}


// Type definition for `dojo_examples::models::Vec2` struct
export interface Vec2 {
    x: number;
    y: number;
}

// Type definition for `dojo_examples::models::Position` struct
export interface Position {
    player: string;
    vec: Vec2;
}


// Type definition for `dojo_examples::models::Moves` struct
export interface Moves {
    player: string;
    remaining: number;
    last_direction: Direction;
}

// Type definition for `dojo_examples::models::Direction` enum
export enum Direction {
    None,
    Left,
    Right,
    Up,
    Down,
}


// Type definition for `dojo_examples::models::EmoteMessage` struct
export interface EmoteMessage {
    identity: string;
    emote: Emote;
}

// Type definition for `dojo_examples::models::Emote` enum
export enum Emote {
    None,
    Happy,
    Sad,
    Angry,
    Love,
}


class BaseCalls {
    contractAddress: string;
    account?: Account;

    constructor(contractAddress: string, account?: Account) {
        this.account = account;
        this.contractAddress = contractAddress;
    }

    async execute(entrypoint: string, calldata: any[] = []): Promise<void> {
        if (!this.account) {
            throw new Error("No account set to interact with dojo_starter");
        }

        await this.account.execute(
            {
                contractAddress: this.contractAddress,
                entrypoint,
                calldata,
            },
            undefined,
            {
                maxFee: 0,
            }
        );
    }
}

class ActionsCalls extends BaseCalls {
    constructor(contractAddress: string, account?: Account) {
        super(contractAddress, account);
    }
    
    async tileTerrain(vec: Vec2): Promise<void> {
        try {
            await this.execute("tile_terrain", [props.vec.x,
                    props.vec.y])
        } catch (error) {
            console.error("Error executing tileTerrain:", error);
            throw error;
        }
    }

    async quadrant(pos: Position): Promise<void> {
        try {
            await this.execute("quadrant", [props.pos.player,
                    props.pos.vec])
        } catch (error) {
            console.error("Error executing quadrant:", error);
            throw error;
        }
    }

    async dojoResource(): Promise<void> {
        try {
            await this.execute("dojo_resource", [])
        } catch (error) {
            console.error("Error executing dojoResource:", error);
            throw error;
        }
    }

    async spawn(): Promise<void> {
        try {
            await this.execute("spawn", [])
        } catch (error) {
            console.error("Error executing spawn:", error);
            throw error;
        }
    }

    async move(direction: Direction): Promise<void> {
        try {
            await this.execute("move", [direction])
        } catch (error) {
            console.error("Error executing move:", error);
            throw error;
        }
    }
}

type Query = Partial<{
    Moved: ModelClause<Moved>;
    Position: ModelClause<Position>;
    Moves: ModelClause<Moves>;
    EmoteMessage: ModelClause<EmoteMessage>;
}>;

type ResultMapping = {
    Moved: Moved;
    Position: Position;
    Moves: Moves;
    EmoteMessage: EmoteMessage;
};

type QueryResult<T extends Query> = {
    [K in keyof T]: K extends keyof ResultMapping ? ResultMapping[K] : never;
};

// Only supports a single model for now, since torii doesn't support multiple models
// And inside that single model, there's only support for a single query.
function convertQueryToToriiClause(query: Query): Clause | undefined {
    const [model, clause] = Object.entries(query)[0];

    if (Object.keys(clause).length === 0) {
        return undefined;
    }

    const clauses: Clause[] = Object.entries(clause).map(([key, value]) => {
        return {
            Member: {
                model,
                member: key,
                ...valueToToriiValueAndOperator(value),
            },
        } satisfies Clause;
    });

    return clauses[0];
}
type GeneralParams = {
    toriiUrl: string;
    relayUrl: string;
    account?: Account;
};

type InitialParams = GeneralParams &
    (
        | {
                rpcUrl: string;
                worldAddress: string;
                actionsAddress: string;
            }
        | {
                manifest: any;
            }
    );

export class DojoExamples {
    rpcUrl: string;
    toriiUrl: string;
    toriiPromise: Promise<Client>;
    relayUrl: string;
    worldAddress: string;
    private _account?: Account;
    actions: ActionsCalls;
    actionsAddress: string;

    constructor(params: InitialParams) {
        this.rpcUrl = LOCAL_KATANA;
        if ("manifest" in params) {
            const config = createManifestFromJson(params.manifest);
            this.worldAddress = config.world.address;

            const actionsAddress = config.contracts.find(
                (contract) =>
                    contract.name === "dojo_starter::systems::actions::actions"
            )?.address;

            if (!actionsAddress) {
                throw new Error("No actions contract found in the manifest");
            }

            this.actionsAddress = actionsAddress;
        } else {
            this.rpcUrl = params.rpcUrl;
            this.worldAddress = params.worldAddress;
            this.actionsAddress = params.actionsAddress;
        }
        this.toriiUrl = params.toriiUrl;
        this.relayUrl = params.relayUrl;
        this._account = params.account;
        this.actions = new ActionsCalls(this.actionsAddress, this._account);

        this.toriiPromise = createClient([], {
            rpcUrl: this.rpcUrl,
            toriiUrl: this.toriiUrl,
            worldAddress: this.worldAddress,
            relayUrl: this.relayUrl,
        });
    }

    get account(): Account | undefined {
        return this._account;
    }

    set account(account: Account) {
        this._account = account;
        this.actions = new ActionsCalls(this.actionsAddress, this._account);
    }

    async query<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        return {
            torii,
            findEntities: async () => this.findEntities(query, limit, offset),
        };
    }

    async findEntities<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        const clause = convertQueryToToriiClause(query);

        const toriiResult = await torii.getEntities({
            limit,
            offset,
            clause,
        });

        return toriiResult as Record<string, QueryResult<T>>;
    }

    async findEntity<T extends Query>(query: T) {
        const result = await this.findEntities(query, 1);

        if (Object.values(result).length === 0) {
            return undefined;
        }

        return Object.values(result)[0] as QueryResult<T>;
    }
}